name: hydromtcp

channels:
  - conda-forge

dependencies:
  - geopandas=0.14.0
  - rasterio=1.3.7
  - hydromt_wflow=0.3.0
  - s3fs
  - boto3
  - pathos
  - pip
  - pip:
    - python-dotenv
    - git+https://github.com/Deltares/hydromt.git
